[package]
name = "mk20"
version = "0.1.0"
authors = ["Shane Leonard <shanel@stanford.edu>"]

[profile.dev]
panic = "abort"
lto = true
opt-level = 0
debug = true

[profile.release]
panic = "abort"
lto = true

[dependencies]
kernel = { path = "../../kernel" }
cortexm4 = { path = "../../arch/cortex-m4" }
capsules = { path = "../../capsules" }
common = { path = "../../common" }
