[package]
name = "tock_rubble"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../../../kernel" }

[dependencies.rubble]
version = "0.0.3"
git = "https://github.com/jonas-schievink/rubble.git"
rev = "1c2014ffe4d674404b8bb2f8f39d7a91a32567d8"
